gitleaks:
  limitEnabled: true
  limit: 0
semgrep:
  severityLimit:
    error:
      enabled: true
      limit: 2
grype:
  # Ignore vulnerabilities with very low Exploit Probability Scores
  epssRiskAcceptance:
    enabled: true
    score: 0.001
  kevLimitEnabled: false
  severityLimit:
    critical:
      enabled: true
      limit: 12
    high:
      enabled: true
      limit: 115
cyclonedx:
  kevLimitEnabled: false
coverage:
  lineThreshold: 0.5
  functionThreshold: 0.5
  branchThreshold: 0.5
