# Base Configuration
version: "1"
imageTag: "us-west1-docker.pkg.dev/holomua-demo/gcp-demo-registry/gcp-demo-ui:latest"
artifactDir: "artifacts"
gatecheckBundleFilename: "gatecheck-bundle.tar.gz"

# Image Build Configuration
imageBuild:
  enabled: true
  buildDir: "."
  dockerfile: "Dockerfile"
  platform: ""
  target: ""
  cacheTo: ""
  cacheFrom: ""
  squashLayers: false
  args: {}

# Image Scan Configuration
imageScan:
  enabled: true
  syftFilename: "syft-sbom-report.json"
  grypeConfigFilename: ""
  grypeFilename: "grype-vulnerability-report-full.json"
  clamavFilename: "clamav-virus-report.txt"

# Code Scan Configuration
codeScan:
  enabled: true
  gitleaksFilename: "gitleaks-secrets-report.json"
  gitleaksSrcDir: "."
  semgrepFilename: "semgrep-sast-report.json"
  semgrepRules: "p/default"
  semgrepExperimental: false
  coverageFile: ""
  semgrepSrcDir: "."

# Image Publish Configuration
imagePublish:
  enabled: false
  bundleTag: "us-west1-docker.pkg.dev/holomua-demo/gcp-demo-registry/gcp-demo-ui/bundle:latest"

# Deploy Configuration
deploy:
  enabled: true
  gatecheckConfigFilename: ".gatecheck.yml"
  submit: true
  successWebhooks:
    - url: "https://belay-api.holomuatech.com/Build/SubmitArtifacts"
      authorizationVar: "DEPLOY_UI_WEBHOOK_AUTH_HEADER"