---                                # yamllint: disable-line rule:document-start
# Simple build → push → deploy pipeline
# Trigger substitutions (set in Cloud Build UI or TF):
#   _SERVICE        demo-api        # or demo-ui
#   _IMAGE_REPO     gcp-demo
#   _REGION         us-west1

steps:
  # ── 1. Build the image ──────────────────────────────────────────
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}

  # ── 2. Deploy to Cloud Run ──────────────────────────────────────
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --project
      - $PROJECT_ID
      - --region
      - ${_REGION}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}
      - --platform
      - managed
      - --allow-unauthenticated   # remove if the service is private
      - --quiet

options:
  substitutionOption: ALLOW_LOOSE
  logStreamingOption: STREAM_ON
  machineType: E2_SMALL

timeout: "900s"
