---                                # yamllint: disable-line rule:document-start
# Trigger substitutions set in Cloud Build UI / TF:
#   _SERVICE        demo-api        # or demo-ui
#   _IMAGE_REPO     gcp-demo
#   _REGION         us-west1

steps:
  # 1. Build the image
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - REACT_APP_API_BASE=${_API_BASE}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}
      - .

  # 2. Push the image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}

  # 3. Reload cloud run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --project
      - $PROJECT_ID
      - --region
      - ${_REGION}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}
      - --platform
      - managed
      - --allow-unauthenticated   # remove if the service is private
      - --quiet

# Tags that Cloud Build should push to Artifact Registry
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _API_BASE: https://demo-api-dev.holomuatech.com
  _REGION: us-west1
  _IMAGE_REPO: gcp-demo
  _SERVICE: demo-ui

timeout: "900s"
