# cloudbuild.yaml  — simple build → push → deploy
# Set these three substitutions in the trigger:
#   _SERVICE        demo-api           or demo-ui
#   _IMAGE_REPO     gcp-demo
#   _REGION         us-west1

steps:
# ── 1. docker build ────────────────────────────────────────────────
- name: gcr.io/cloud-builders/docker
  args: [
    "build",
    "-t",
    "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}",
    "."
  ]

# Cloud Build will push automatically because the tag is in `images:`
images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}"

# ── 2. deploy to Cloud Run ────────────────────────────────────────
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [
    "run", "deploy", "${_SERVICE}",
    "--project", "$PROJECT_ID",
    "--region", "${_REGION}",
    "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_SERVICE}:${SHORT_SHA}",
    "--platform", "managed",
    "--allow-unauthenticated",
    "--quiet"
  ]

options:
  logStreamingOption: STREAM_ON
  substitutionOption: ALLOW_LOOSE
  machineType: E2_SMALL

timeout: "900s"

